In [1]:
from scipy.stats import ttest_ind
import numpy as np
from utils import partition
from perm_test import permInterval, pval, tconf

In [8]:
n, n1, n2 = 2, 12, 8
np.random.seed(123)
x1s = np.random.normal(size=(n, n1))
x2s = np.random.normal(size=(n, n2))
ts = ttest_ind(x1s, x2s, axis=-1).statistic
ts

array([0.9910469, 1.9078664])

In [9]:
x1, x2 = x1s[0], x2s[0]
t_obs = ttest_ind(x1, x2, axis=-1).statistic
t_obs

0.9910469006146199

In [10]:
t_obs == ts

array([ True, False])

In [11]:
parts = partition(n1, n2)
parts

array([[ 0,  1,  2, ..., 17, 18, 19],
       [ 0,  1,  2, ..., 17, 18, 19],
       [ 0,  1,  2, ..., 17, 18, 19],
       ...,
       [ 7,  8, 10, ...,  5,  6,  9],
       [ 7,  9, 10, ...,  5,  6,  8],
       [ 8,  9, 10, ...,  5,  6,  7]])

In [12]:
permInterval(x1, x2, parts, 0)

True