In [1]:
using Random
using Distributions
using FLoops
using Base.Threads

include("data.jl")
include("util.jl")

include("intervals/permutation.jl")
include("intervals/bootstrap.jl")
include("intervals/t.jl")

Threads.nthreads()

112

In [2]:
"""
DATA CONFIG
"""
alpha = 0.05

# data
B  = 100    # num. coverage probabilities per boxplot
S  = 1825   # num. samples per coverage probability
nx = 15      # size of group 1
ny = 8     # size of group 2
px, py = partition(nx, ny)
mc_size = try
    (binomial(nx+ny, nx) > 45_000) ? 10_000 : 0
catch
    0
end

# ALWAYS USE EXACT ENUMERATION FOR NOW
# mc_size = 0

dtype = Float32
seed = 123

123

In [4]:
"""
POPULATION SETTINGS
"""

Random.seed!(123)

distrTypeX = Normal{dtype}
X_mu = dtype.(round.(rand(B), digits=3))
X_sigma = dtype.(round.(rand(B), digits=3))
distrX = map(distrTypeX, X_mu, X_sigma)

distrTypeY = Normal{dtype}
Y_mu = X_mu
Y_sigma = dtype.(rand(Uniform(2, 5), B)) .* X_sigma
distrY = map(distrTypeY, Y_mu, Y_sigma);

In [5]:
deltas = @. mean(distrX) - mean(distrY)

@show distrX[1:2]
@show distrY[1:2]
@show deltas[1:2];

distrX[1:2] = Normal{Float32}[Normal{Float32}(μ=0.906f0, σ=0.954f0), Normal{Float32}(μ=0.443f0, σ=0.846f0)]
distrY[1:2] = Normal{Float32}[Normal{Float32}(μ=0.906f0, σ=4.669853f0), Normal{Float32}(μ=0.443f0, σ=1.8714627f0)]
deltas[1:2] = Float32[0.0, 0.0]


In [6]:
Random.seed!(123)
xs = [dtype.(rand(distrX[i], nx, S)) for i in 1:B]
ys = [dtype.(rand(distrY[i], ny, S)) for i in 1:B]
@show size(ys)
ys[2]

size(ys) = (100,)


8×1825 Matrix{Float32}:
 -1.78828    0.73302   -3.79254   …  -0.571954   1.16034   -0.635054
  0.534212  -1.61319    0.523947      4.32314   -0.279999   0.192816
  1.53054    1.93085   -0.610183      3.77093   -1.50322   -3.48768
 -0.55091   -0.231934  -1.78947      -0.353758   0.268195   2.51508
 -0.501891   1.15176    0.720626     -0.473422  -3.18394    1.84716
 -2.81796    2.42611   -0.835204  …  -1.19419    1.48002   -2.11514
 -3.38576   -2.79629    0.95497       1.851     -1.89577    1.59796
 -1.1039    -0.41798    0.310042      0.99545   -0.234913   0.91139

In [7]:
# flatten into 3D matrix
X = reshape(hcat(xs...), nx, S, B)
Y = reshape(hcat(ys...), ny, S, B)
Y[:,:,2]

8×1825 Matrix{Float32}:
 -1.78828    0.73302   -3.79254   …  -0.571954   1.16034   -0.635054
  0.534212  -1.61319    0.523947      4.32314   -0.279999   0.192816
  1.53054    1.93085   -0.610183      3.77093   -1.50322   -3.48768
 -0.55091   -0.231934  -1.78947      -0.353758   0.268195   2.51508
 -0.501891   1.15176    0.720626     -0.473422  -3.18394    1.84716
 -2.81796    2.42611   -0.835204  …  -1.19419    1.48002   -2.11514
 -3.38576   -2.79629    0.95497       1.851     -1.89577    1.59796
 -1.1039    -0.41798    0.310042      0.99545   -0.234913   0.91139

In [16]:
function save_ci_results(results, methodId, B, S, pooled=nothing, two_sided=nothing; prefix="", dir="./")
    averages = []

    for batchId in 1:B
        batch = results[methodId, batchId, :]
        coverage = sum([j for (j, _) in batch]) / S
        width = sum([j for (_, j) in batch]) / S
        push!(averages, (coverage, width))
    end
    if isnothing(two_sided)
        save(averages, distrX[1:B], distrY[1:B], alpha, prefix=prefix, dir=dir)
    else
        alpha_ = two_sided ? alpha : alpha / 2
        save(averages, distrX[1:B], distrY[1:B], alpha_, pooled, two_sided, prefix=prefix, dir=dir)
    end
end

function save_permutation_results(results, B, S; prefix="", dir="./")
    i = 1
    per_method = []
    for two_sided in [true, false]
        for pooled in [true, false]
            save_ci_results(results, i, B, S, pooled, two_sided, prefix=prefix, dir=dir)
            i += 1
        end
    end
end

save_permutation_results (generic function with 1 method)

In [9]:
B = 100
S = 1825

T = Threads.nthreads()
results = Array{Union{Nothing, Tuple}, 3}(undef, 6, B, S)
fill!(results, nothing)
mc_size = 0

#@time Threads.@threads for (i,j) in collect(Iterators.product(1:B, 1:S)) # 15.52 sec on (B,S) = (5, 1800)
@time @floop ThreadedEx(basesize=div(B*S, T)) for b in 1:B, s in 1:S
    @inbounds x = X[:,s,b]
    @inbounds y = Y[:,s,b]

    """ 
    results[1, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), true, alpha, twoSided, twoSided)    
    results[2, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), false, alpha, twoSided, twoSided)
    results[3, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), true, alpha/2, greater, smaller, 0.0005)
    results[4, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), false, alpha/2, greater, smaller, 0.0005)
    
    """
    results[5, b, s] = bootstrap(x, y, deltas[b], alpha, nsamples=10_000)
    #results[6, b, s] = tconf(x, y, deltas[b], alpha, false)
end

dir = "../results/" * string(nx) * "_" * string(ny) * "/4/"
save_ci_results(results, 6, B, S; prefix="bs", dir=dir)
#save_permutation_results(results, B, S; dir=dir)

2444.616497 seconds (3.84 G allocations: 408.328 GiB, 93.13% gc time, 0.30% compilation time)


LoadError: MethodError: no method matching iterate(::Nothing)
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at /opt/julia-1.7.1/share/julia/base/range.jl:826
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at /opt/julia-1.7.1/share/julia/base/range.jl:826
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at /opt/julia-1.7.1/share/julia/base/dict.jl:695
  ...

In [ ]:
save_ci_results(results, 5, B, S; prefix="bs", dir=dir)

In [76]:
averages = []
for row in eachrow(results[5,:,:])
    coverage = sum([j for (j, _) in row]) / S
    width = sum([j for (_, j) in row]) / S
    push!(averages, (coverage, width))
end
averages

5-element Vector{Any}:
 (0.9041095890410958, 1.7169137288119696)
 (0.8964383561643836, 1.5188572278067674)
 (0.9057534246575343, 1.0491979467480967)
 (0.8997260273972603, 0.21909246020121118)
 (0.9145205479452054, 0.2478563258378473)

---

In [70]:
x = X[:,1,1]
y = Y[:,1,1]
@time permInterval(x, y, deltas[1], (px, py, 0), true, alpha, twoSided, twoSided)

permInterval(x, y, deltas[1], (px, py, 0), true, alpha/2, greater, smaller)

pval(x, y, 2.4218399175319254, (px, py, 0), true, twoSided)

  0.292847 seconds (510.31 k allocations: 55.944 MiB, 93.62% compilation time)


0.05034965f0