In [1]:
using Random
using Distributions
using FLoops
using Base.Threads

include("data.jl")
include("util.jl")

include("intervals/permutation.jl")
include("intervals/bootstrap.jl")
include("intervals/t.jl")

Threads.nthreads()

112

In [5]:
rand(Uniform(1, 10), 10)

10-element Vector{Float64}:
 5.305727856440202
 1.3165361783826628
 4.658085973094793
 8.621722650262056
 7.762316680662818
 6.259344789631702
 3.3868211484445165
 2.6661536809118376
 4.4440444127712535
 3.696200463087836

In [13]:
"""
DATA CONFIG
"""
alpha = 0.05

# data
B  = 100    # num. coverage probabilities per boxplot
S  = 1825   # num. samples per coverage probability
nx = 8      # size of group 1
ny = 8     # size of group 2
px, py = partition(nx, ny)
mc_size = try
    (binomial(nx+ny, nx) > 45_000) ? 10_000 : 0
catch
    0
end

dtype = Float32
seed = 123

"""
POPULATION SETTINGS
"""

Random.seed!(seed)

distrTypeX = Normal{dtype}
X_mu = dtype.(round.(rand(B), digits=3))
X_sigma = dtype.(round.(rand(B), digits=3))
distrX = map(distrTypeX, X_mu, X_sigma)

distrTypeY = Normal{dtype}
Y_mu = X_mu
Y_sigma = dtype.(rand(Uniform(2, 5), B)) .* X_sigma
distrY = map(distrTypeY, Y_mu, Y_sigma)

@show distrX[1:2]
@show distrY[1:2]

deltas = @. mean(distrX) - mean(distrY);

distrX[1:2] = Normal{Float32}[Normal{Float32}(μ=0.906f0, σ=0.954f0), Normal{Float32}(μ=0.443f0, σ=0.846f0)]
distrY[1:2] = Normal{Float32}[Normal{Float32}(μ=0.906f0, σ=4.669853f0), Normal{Float32}(μ=0.443f0, σ=1.8714627f0)]


In [14]:
Random.seed!(123)
xs = [dtype.(rand(distrX[i], nx, S)) for i in 1:B]
ys = [dtype.(rand(distrY[i], ny, S)) for i in 1:B]
@show size(ys)
ys[2]

size(ys) = (100,)


8×1825 Matrix{Float32}:
 -0.266106   2.24199    1.77805   …  -0.385481   4.77009    1.13052
  4.11802   -0.706996  -0.356081      0.552066  -3.59045    2.4257
  2.31829    0.593428   3.14608       0.647509  -0.220311  -0.197421
  1.41488    0.505523  -3.47063      -0.983018   0.387133   0.226448
  0.625931   2.78857   -0.100655      1.7088     1.82707    0.225094
  0.121556   1.45671    1.07035   …  -0.900813  -0.620921   0.513558
  0.03956   -0.706514  -1.22506       1.02886    1.55326   -0.71521
 -0.833561   0.554825   2.14267      -2.36663    0.849666  -0.162708

In [15]:
# flatten into 3D matrix
X = reshape(hcat(xs...), nx, S, B)
Y = reshape(hcat(ys...), ny, S, B)
Y[:,:,2]

8×1825 Matrix{Float32}:
 -0.266106   2.24199    1.77805   …  -0.385481   4.77009    1.13052
  4.11802   -0.706996  -0.356081      0.552066  -3.59045    2.4257
  2.31829    0.593428   3.14608       0.647509  -0.220311  -0.197421
  1.41488    0.505523  -3.47063      -0.983018   0.387133   0.226448
  0.625931   2.78857   -0.100655      1.7088     1.82707    0.225094
  0.121556   1.45671    1.07035   …  -0.900813  -0.620921   0.513558
  0.03956   -0.706514  -1.22506       1.02886    1.55326   -0.71521
 -0.833561   0.554825   2.14267      -2.36663    0.849666  -0.162708

In [16]:
function save_permutation_results(results, B, S, dir="./")
    i = 1
    per_method = []
    for is_two_sided in [true, false]
        for pooled in [true, false]
            averages = []

            for row in eachrow(results[i,:,:])
                coverage = sum([j for (j, _) in row]) / S
                width = sum([j for (_, j) in row]) / S
                push!(averages, (coverage, width))
            end

            alpha_ = is_two_sided ? alpha : alpha / 2
            save(averages, distrX[1:B], distrY[1:B], alpha_, pooled, is_two_sided, parent_dir=dir)
            i += 1
        end
    end
end

save_permutation_results (generic function with 2 methods)

In [18]:
B = 100
S = 1825

T = Threads.nthreads()
results = Array{Union{Nothing, Tuple}, 3}(undef, 6, B, S)
fill!(results, nothing)

#@time Threads.@threads for (i,j) in collect(Iterators.product(1:B, 1:S)) # 15.52 sec on (B,S) = (5, 1800)
@time @floop ThreadedEx(basesize=div(B*S, T)) for b in 1:B, s in 1:S
    @inbounds x = X[:,s,b]
    @inbounds y = Y[:,s,b]

    results[1, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), true, alpha, twoSided, twoSided)    
    results[2, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), false, alpha, twoSided, twoSided)
    results[3, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), true, alpha/2, greater, smaller, 0.0005)
    results[4, b, s] = permInterval(x, y, deltas[b], (px, py, mc_size), false, alpha/2, greater, smaller, 0.0005)
    
    """
    lo, hi = bootstrap(x, y, 0.05, false, 10_000)
    coverages[5] += (lo <= delta <= hi)

    lo, hi = tconf(x, y, 0.05, false)
    coverages[6] += (lo <= delta <= hi)
    """
end

save_permutation_results(results, B, S, "../results/permutation/4/")

2378.407456 seconds (1.37 G allocations: 15.048 TiB, 69.14% gc time, 0.68% compilation time)


---

In [28]:
averages = []
for row in eachrow(results[1,:,:])
    coverage = sum([j for (j, _) in row]) / S
    width = sum([j for (_, j) in row]) / S
    push!(averages, (coverage, width))
end
averages

5-element Vector{Any}:
 (0.95, 3.1827745949945476)
 (0.92, 1.6322506846556246)
 (0.85, 1.3739451044574138)
 (0.93, 0.21217739206443034)
 (0.9, 0.18690359039665994)

In [70]:
x = X[:,1,1]
y = Y[:,1,1]
@time permInterval(x, y, deltas[1], (px, py, 0), true, alpha, twoSided, twoSided)

permInterval(x, y, deltas[1], (px, py, 0), true, alpha/2, greater, smaller)

pval(x, y, 2.4218399175319254, (px, py, 0), true, twoSided)

  0.292847 seconds (510.31 k allocations: 55.944 MiB, 93.62% compilation time)


0.05034965f0